Repository ETS-Winter-2024-CUT/INF111-Exemples_Java, pull requests merged in 2024-01, with the labels that each got.

#1 Ajout de l'exemple "Hello World" en Java
  src/HelloWorld.java
Labels: enhancement, good first issue

#3 Ajout d'un linter et de son Workflow pour l'intégration continue
  .github/workflows/java-linter.yml
  linter.py
Labels: devops

#4 Ajout du fichier modèle pour les PRs
  .github/pull_request_template.md
Labels: documentation

#5 Correction du lien de clonage du repo
  README.md
Labels: documentation

#13 Ajout d'un exercice de manipulation d'un tableau
  src/ManipulationListeEntiers.java
Labels: enhancement, good first issue

#12 Ajout de l'exercice d'affichage de la plus grande valeur de n valeurs données
  src/MaxN.java
Labels: enhancement

#15 Ajout de divers exemples avec des explications détaillées
  src/GUI_intro.java
  src/MaxN.java
  src/expressions.java
  src/math_class.java
  src/random_numbers.java
  src/user_input.java
  src/variables.java
Labels: enhancement

#2 Ajout de l'exerice de calcul d'un salaire
  src/CalculSalaire.java
Labels: enhancement

#9 Ajout de l'exercice de traduction d'une note en note litérale
  src/NotationLiterale.java
Labels: enhancement

#6 Ajout de l'exercice de calcule d'une somme entre des bornes
  src/SommeEntreBornes.java
Labels: enhancement

#8 Ajout de l'exercice de calcul d'une facture (Ex: Coop ÉTS)
  src/PrixCoopETS.java
Labels: enhancement

#7 Ajout de l'exercice de validation d'une valeur entre deux bornes constantes
  src/ValiderEntreBornesConstantes.java
Labels: enhancement

#11 Ajout de l'exercice sur les boucles "for"
  src/BoucleFor.java
Labels: enhancement

#10 Ajout de l'exercice de nombre de jours à une date donnée
  src/Expressions.java
  src/GUI_intro.java
  src/Math_class.java
  src/NombreJoursADate.java
  src/RandomNumbers.java
  src/UserInput.java
  src/Variables.java
Labels: enhancement, good first issue
